# Generated by Django 6.0 on 2025-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0003_alter_customer_cccd_alter_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cccd',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
