# Generated by Django 5.2 on 2025-12-15 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được chứa chữ số.', regex='^\\d+$')]),
        ),
    ]
