# Generated by Django 5.2.8 on 2025-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0013_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "speech",
                    models.CharField(default="Xin chào! Tôi là Toki!", max_length=255),
                ),
                ("image", models.ImageField(upload_to="mascots/")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
