# Generated by Django 6.0 on 2025-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0002_alter_customer_address_alter_customer_cccd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('approved', 'Chờ Duyệt'), ('pending', 'Đang xử lý'), ('completed', 'Hoàn tất')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
