# Generated by Django 6.0 on 2025-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0004_alter_customer_cccd_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='tax_code',
            field=models.IntegerField(max_length=20),
        ),
    ]
