# Generated by Django 6.0 on 2025-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0005_alter_businessregistrationservice_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
