# Generated by Django 6.0 on 2025-12-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0006_alter_businessregistrationservice_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherservice',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
