# Generated by Django 5.2 on 2025-12-15 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0009_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Trường này chỉ được nhập số', regex='^\\d+$')], verbose_name='Số CCCD'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('personal', 'Cá nhân'), ('company', 'Doanh nghiệp')], default='personal', max_length=20, verbose_name='Loại khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager',
            field=models.CharField(max_length=255, verbose_name='Người phụ trách'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('approved', 'Chờ duyệt'), ('pending', 'Đang xử lý'), ('completed', 'Hoàn tất')], default='approved', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Trường này chỉ được nhập số', regex='^\\d+$')], verbose_name='Mã số thuế'),
        ),
    ]
