# Generated by Django 5.2.8 on 2025-12-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0012_alter_businessregistrationservice_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="sliders/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
