# Generated by Django 5.2 on 2025-12-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0014_mascot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trademarks', to='ipshieldapp.contract'),
        ),
    ]
