# Generated by Django 5.2 on 2025-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0015_alter_trademarkservice_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
    ]
