# Generated by Django 5.2 on 2025-12-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0016_trademarkservice_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkservice',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyrights', to='ipshieldapp.contract'),
        ),
    ]
