# Generated by Django 5.2 on 2025-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0017_remove_trademarkservice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/'),
        ),
        migrations.AlterField(
            model_name='copyrightservice',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/'),
        ),
        migrations.AlterField(
            model_name='investmentservice',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/'),
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='trademark_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/trademark/'),
        ),
    ]
