# Generated by Django 6.0 on 2025-12-26 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0018_alter_businessregistrationservice_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Hợp đồng', 'verbose_name_plural': 'Hợp đồng'},
        ),
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'ordering': ['contract', 'installment_no'], 'verbose_name': 'Đợt thanh toán', 'verbose_name_plural': 'Các đợt thanh toán'},
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn thanh toán'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='installment_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nhập số đợt thanh toán (VD: 2, 3, 4, 5...)', null=True, verbose_name='Số đợt thanh toán'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Trả dứt điểm'), ('installment', 'Trả nhiều đợt')], max_length=20, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='Nhập số tiền thanh toán cho đợt này', max_digits=15, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='installment_no',
            field=models.PositiveSmallIntegerField(verbose_name='Đợt thứ'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_no'], name='ipshieldapp_contrac_dc9907_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['customer', 'status'], name='ipshieldapp_custome_2f7a66_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='ipshieldapp_created_54746a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['contract', 'is_paid'], name='ipshieldapp_contrac_7d2d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['paid_date'], name='ipshieldapp_paid_da_f27774_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['due_date'], name='ipshieldapp_due_dat_40f57b_idx'),
        ),
    ]
