# Generated by Django 6.0 on 2025-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0019_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đã thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền đợt'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
