# Generated by Django 6.0 on 2025-12-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0020_paymentinstallment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền đợt'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đã thanh toán'),
        ),
    ]
