# Generated by Django 6.0 on 2025-12-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0021_alter_paymentinstallment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='installment_count',
        ),
        migrations.AddField(
            model_name='contract',
            name='prepaid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Số tiền trả trước'),
        ),
    ]
