# Generated by Django 6.0 on 2025-12-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0022_remove_contract_installment_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'ordering': ['contract'], 'verbose_name': 'Đợt thanh toán', 'verbose_name_plural': 'Các đợt thanh toán'},
        ),
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền đợt thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Đã thanh toán'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Số tiền đã trả'),
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='installment_no',
        ),
    ]
