# Generated by Django 6.0 on 2025-12-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0023_alter_paymentinstallment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=15)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='ipshieldapp.contract')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ipshieldapp.paymentinstallment')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
