# Generated by Django 6.0 on 2025-12-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0024_paymentlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyalCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(upload_to="loyal_customers/")),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
