# Generated by Django 6.0 on 2025-12-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0025_loyalcustomer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loyalcustomer",
            options={
                "ordering": ["order"],
                "verbose_name": "Khách hàng thân thiết",
                "verbose_name_plural": "Khách hàng thân thiết",
            },
        ),
        migrations.AlterField(
            model_name="loyalcustomer",
            name="image",
            field=models.ImageField(upload_to="loyal_customers/", verbose_name="Ảnh"),
        ),
        migrations.AlterField(
            model_name="loyalcustomer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Kích hoạt"),
        ),
        migrations.AlterField(
            model_name="loyalcustomer",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tên khách hàng"
            ),
        ),
        migrations.AlterField(
            model_name="loyalcustomer",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Thứ tự hiển thị"
            ),
        ),
        migrations.AlterField(
            model_name="loyalcustomer",
            name="role",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Vai trò/Chức vụ"
            ),
        ),
    ]
