# Generated by Django 6.0 on 2026-01-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0026_alter_loyalcustomer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NhanHieuDocQuyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tên nhãn hiệu"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="logokhachhang/logobrand/",
                        verbose_name="Ảnh nhãn hiệu",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hiển thị"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nhãn hiệu độc quyền",
                "verbose_name_plural": "Nhãn hiệu độc quyền",
            },
        ),
        migrations.DeleteModel(
            name="LoyalCustomer",
        ),
    ]
