# Generated by Django 6.0 on 2026-01-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0027_nhanhieudocquyen_delete_loyalcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='bill_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='is_exported_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='paid_at',
            field=models.DateTimeField(verbose_name='Thời gian thanh toán'),
        ),
    ]
