# Generated by Django 6.0 on 2026-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0029_alter_businessregistrationservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán'),
        ),
    ]
