# Generated by Django 6.0 on 2026-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0030_contract_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistrationservice',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/', verbose_name='File chứng nhận đăng ký'),
        ),
    ]
