# Generated by Django 6.0 on 2026-01-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0031_businessregistrationservice_registration_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='images/registration_certificates/', verbose_name='File chứng nhận đăng ký kinh doanh'),
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài liệu')),
                ('file', models.FileField(upload_to='images/attachments/', verbose_name='File đính kèm')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ipshieldapp.contract', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Tài liệu đính kèm',
                'verbose_name_plural': 'Tài liệu đính kèm',
            },
        ),
    ]
