# Generated by Django 6.0 on 2026-01-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0032_alter_businessregistrationservice_registration_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/trademark/')),
                ('name', models.CharField(max_length=255)),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ipshieldapp.trademarkservice')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractAttachment',
        ),
    ]
