# Generated by Django 6.0 on 2026-01-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0033_trademarkattachment_delete_contractattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/business/')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ipshieldapp.businessregistrationservice')),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/copyright/')),
                ('name', models.CharField(max_length=255)),
                ('copyright', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ipshieldapp.copyrightservice')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/investment/')),
                ('name', models.CharField(max_length=255)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ipshieldapp.investmentservice')),
            ],
        ),
    ]
