# Generated by Django 6.0 on 2026-01-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0034_businessattachment_copyrightattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/other_service/')),
                ('name', models.CharField(max_length=255)),
                ('other_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ipshieldapp.otherservice')),
            ],
        ),
    ]
