# Generated by Django 6.0 on 2026-01-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ipshieldapp', '0035_otherserviceattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyrightattachment',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='investmentattachment',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='otherserviceattachment',
            name='other_service',
        ),
        migrations.RemoveField(
            model_name='trademarkattachment',
            name='trademark',
        ),
        migrations.RemoveField(
            model_name='businessregistrationservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='copyrightservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='investmentservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='otherservice',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='trademarkservice',
            name='certificate_file',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID đối tượng')),
                ('certificate_file', models.FileField(upload_to='images/certificates/', verbose_name='File chứng nhận')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
            ],
            options={
                'verbose_name': 'Tài liệu đính kèm',
                'verbose_name_plural': 'Tài liệu đính kèm',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='BusinessAttachment',
        ),
        migrations.DeleteModel(
            name='CopyrightAttachment',
        ),
        migrations.DeleteModel(
            name='InvestmentAttachment',
        ),
        migrations.DeleteModel(
            name='OtherServiceAttachment',
        ),
        migrations.DeleteModel(
            name='TrademarkAttachment',
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['content_type', 'object_id'], name='ipshieldapp_content_3eee72_idx'),
        ),
    ]
