# Generated by Django 6.0 on 2026-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0036_remove_copyrightattachment_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default=True, upload_to='images/certificates/', verbose_name='File đính kèm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên file'),
        ),
    ]
