# Generated by Django 5.2 on 2026-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipshieldapp", "0038_alter_paymentinstallment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademarkservice",
            name="valid_date",
            field=models.DateField(
                blank=True,
                help_text="Ngày đơn được xác nhận hợp lệ",
                null=True,
                verbose_name="Ngày hợp lệ hóa đơn",
            ),
        ),
    ]
