# Generated by Django 6.0 on 2026-01-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0039_trademarkservice_valid_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='ipshieldapp_contrac_7363e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='ipshieldapp_install_b85045_idx',
        ),
        migrations.DeleteModel(
            name='PaymentLog',
        ),
    ]
