# Generated by Django 6.0 on 2026-01-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0040_remove_paymentlog_ipshieldapp_contrac_7363e6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='bill_exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất hóa đơn'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='is_exported_bill',
            field=models.BooleanField(default=False, verbose_name='Đã xuất hóa đơn'),
        ),
    ]
