# Generated by Django 6.0 on 2026-01-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0041_paymentinstallment_bill_exported_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='bill_exported_at',
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='is_exported_bill',
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền thanh toán')),
                ('paid_at', models.DateTimeField(verbose_name='Thời gian thanh toán')),
                ('is_exported_bill', models.BooleanField(default=False, verbose_name='Đã xuất hóa đơn')),
                ('bill_exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất hóa đơn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='ipshieldapp.contract', verbose_name='Hợp đồng')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ipshieldapp.paymentinstallment', verbose_name='Đợt thanh toán')),
            ],
            options={
                'verbose_name': 'Lịch sử thanh toán',
                'verbose_name_plural': 'Lịch sử thanh toán',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['contract', '-paid_at'], name='ipshieldapp_contrac_7363e6_idx'), models.Index(fields=['installment', '-paid_at'], name='ipshieldapp_install_b85045_idx')],
            },
        ),
    ]
