# Generated by Django 5.2 on 2025-12-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('nhanhieu', 'Đăng ký nhãn hiệu'), ('banquyen', 'Bản quyền tác giả'), ('dkkd', 'Đăng ký kinh doanh'), ('dautu', 'Đăng ký đầu tư'), ('khac', 'Dịch vụ khác')], max_length=50)),
                ('contract_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('paused', 'Ngưng')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('personal', 'Cá nhân'), ('company', 'Doanh nghiệp')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Ngưng hoạt động'), ('pending', 'Chờ xử lý')], default='active', max_length=20)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cccd', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRegistrationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('tax_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('legal_representative', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('charter_capital', models.CharField(max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/images/certificates/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='ipshieldapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ipshieldapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('owner_address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('certificate_no', models.CharField(max_length=50)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/images/certificates/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copyright', to='ipshieldapp.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ipshieldapp.customer'),
        ),
        migrations.CreateModel(
            name='InvestmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100)),
                ('investor', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('total_capital', models.CharField(max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/images/certificates/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='ipshieldapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('legal_representative', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/images/certificates/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_service', to='ipshieldapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='TrademarkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('app_no', models.CharField(max_length=50)),
                ('filing_date', models.DateField()),
                ('trademark_name', models.CharField(max_length=255)),
                ('trademark_image', models.ImageField(blank=True, null=True, upload_to='static/images/trademark/')),
                ('classification', models.TextField()),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='static/images/certificates/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trademark', to='ipshieldapp.contract')),
            ],
        ),
    ]
