# Generated by Django 5.2 on 2025-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0007_alter_otherservice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
