# Generated by Django 5.2 on 2025-12-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0010_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=15, verbose_name='Giá trị hợp đồng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='installment_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '3 đợt'), (6, '6 đợt')], null=True, verbose_name='Số đợt thanh toán'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Trả dứt điểm'), ('installment', 'Trả góp')], default=True, max_length=20, verbose_name='Hình thức thanh toán'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveSmallIntegerField(verbose_name='Đợt')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='ipshieldapp.contract')),
            ],
            options={
                'verbose_name': 'Đợt thanh toán',
                'verbose_name_plural': 'Các đợt thanh toán',
                'unique_together': {('contract', 'installment_no')},
            },
        ),
    ]
