# Generated by Django 5.2 on 2025-12-17 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipshieldapp', '0011_contract_contract_value_contract_installment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessregistrationservice',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='phone',
            field=models.CharField(default=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trademarkservice',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Số điện thoại chỉ được nhập chữ số', regex='^\\d+$')], verbose_name='Số điện thoại'),
        ),
    ]
